server:
  port: 10016
  servlet:
    session:
      # \u8BBE\u7F6E\u670D\u52A1\u7AEFsession\u7684\u8FC7\u671F\u65F6\u95F4\u4E3A1\u5206\u949F
      timeout: 1

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

mybatis:
  mapper-location: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
